services:

  hoverfly:
    image: spectolabs/hoverfly:v1.11.1
    ports:
      - "8500:8500"
      - "8888:8888"
    volumes:
      - "./simulations:/hoverfly/simulations"
    command:
      - "-import"
      - "/hoverfly/simulations/${IMPORT_FILE:-streamed.json}"
      - "-webserver"
    environment:
      - HOVERFLY_BASE_URL=http://hoverfly:8500

  node-proxy:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - hoverfly
    env_file:
      - .env